src/router.js
=> teste commit

page/inscription.html, page/payment.html, src/inscription.js, src/payment.js, src/router.js, style/home.css, style/inscription.css, style/payment.css
=> add pagamento

src/payment.js, src/router.js
=> troca das url

src/payment.js, vercel.json
=> add da rota

vercel.json
=> mudando vercel

vercel.json
=> troca do vercel

vercel.json
=> novo vercel.json

vercel.json
=> tentando novamente

page/documentation.html, page/home.html, page/inscription.html, page/payment.html, src/payment.js, style/inscription.css
=> troca da url

page/documentation.html, page/home.html, page/inscription.html
=> troca de url para home

page/payment.html, src/payment.js, style/payment.css
=> reformulação de pagamento

page/inscription.html, src/inscription.js, src/payment.js, src/router.js, style/inscription.css
=> mudança da incricao

page/payment.html, style/payment.css
=> add responsividade da tela payments

style/inscription.css
=> resposivo a inscrição

page/payment.html
=> add de class no form

src/payment.js
=> retirada do init duas vezes

page/inscription.html, src/inscription.js, style/inscription.css
=> add participacao

page/inscription.html, page/payment.html, src/inscription.js, src/payment.js, style/inscription.css, style/payment.css
=> add de novas funções

src/inscription.js, style/inscription.css
=> reformulação da inscição

src/inscription.js
=> troca no buttonpayment

src/inscription.js
=> adição de verificação se vai ter hospedagem

src/inscription.js
=> troca para uma url padrao no  buttonpayment

vercel.json
=> reformulado o vercel.json para pegar as imagens

src/inscription.js
=> consertado o form-container

page/inscription.html, page/payment.html, src/inscription.js, src/payment.js, style/inscription.css, style/payment.css
=> add do loading

style/inscription.css, style/payment.css
=> responsivo o loading

page/documentation.html
=> melhoria dos campos p

page/home.html, page/inscription.html, src/inscription.js, style/inscription.css
=> Ajuste dos campos no html

src/inscription.js
=> ajuste no nome irmãs

vercel.json
=> atualizacao do vercel para a tela de dashboard

src/dashboard.js, style/dashboard.css
MELHORIAS NA TELA DE DASHBOARD
=> TRATAMENTO DE DADOS NA TELA E PARTE VISUAL

page/dashboard.html, page/loginManagement.html, src/loginManagement.js, src/router.js, style/loginManagement.css
=> add do login

page/report.html, src/report.js, src/router.js, style/report.css
=> inclusão da tela de relatorio

vercel.json
=> insclusão da rota do relatorio

page/inscription.html, src/inscription.js, style/inscription.css
=> adição de logica para localidade

src/inscription.js
=> retirada do disble

src/inscription.js
=> Feature mt

src/inscription.js
=> mudança no objeto

src/inscription.js
=> troca na linha 255

src/payment.js
=> adicionado o url com localidade

page/payment.html, style/payment.css
=> adição dos dados de pagamento

style/payment.css
=> responsividade reformulada

style/payment.css
=> ajeitado o tamanho dos dados do pagamento

vercel.json
=> ajeitando bug da rota de hospedagem

src/hostingPage.js, style/hostingPage.css
=> add da responsividade na tela de hospedagem

page/payment.html
=> troca dos dados da conta pix

page/payment.html
=> adicionando dados do pagamento

page/payment.html, style/payment.css
=> troca da formataçao do dados pix

page/hostingPage.html, src/hostingPage.js, style/hostingPage.css
=> adição do dark mode na tela de hospedagem

page/hostingPage.html, style/hostingPage.css
=> retirada de algumas marcações

page/hostingPage.html, style/hostingPage.css
=> troca da cor do suggestion-item

style/hostingPage.css
=> aumento do height do list-head

src/inscription.js
=> adição do tratamento de dados do

page/proofPayment.html, src/proofPayment.js, src/router.js, style/proofPayment.css, vercel.json
=> add da rota de comprovantes

page/registro_pagamentos.html, src/registro_pagamentos.js, style/loginManagement.css, style/registro_pagamentos.css
=> subindo tela de inscrição, ticket e movimentação

page/inscriptionError.html, style/inscriptionError.css, vercel.json
=> troca de rota para inscrição encerrada

page/registro_pagamentos.html, src/registro_pagamentos.js, style/registro_pagamentos.css
=> atualização do registro_pagamento

page/payment.html, src/payment.js
=> add de bloqueio para pdf's
